services:
  # Platform API
  api:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: seeableweb-platform-api:latest
    container_name: platform
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
      - ./.docker/php.ini:/etc/php/8.4/fpm/conf.d/99-php.ini
      - ./.docker/xdebug.ini:/etc/php/8.4/cli/conf.d/20-xdebug.ini
      - ./.docker/fpm-pool.conf:/usr/local/etc/php-fpm.conf
      - ~/.ssh:/home/laravel/.ssh
    cap_add:
      - SYS_ADMIN
    environment:
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=host.docker.internal}
    depends_on:
      - db
      - redis
      - mail
    networks:
      - default-network

  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - default-network

  # Database
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-laravel}
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --innodb-buffer-pool-size=2G
      - --innodb-log-file-size=512M
    networks:
      - default-network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data
    networks:
      - default-network

  # Mail
  mail:
    image: axllent/mailpit:latest
    container_name: mail
    restart: unless-stopped
    ports:
      - ${MAIL_PORT:-1025}:1025
      - 8025:8025
    networks:
      - default-network

# Networks
networks:
  default-network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
